Número=int(input("Digite o número:"))
if Número % 2 ==0: #se o numero dividido por dois é zero...
    print(f"0 número {Número} Par") #mostrar que ele é "par"...
else: #senão...
    print(f"0 número {Número} impar") # mostrar que ele é ímpar...